SUPPORTED_LANGUAGES = [
    "English",
    "Hindi",
    "Konkani",
    "Kannada",
    "Dogri",
    "Bodo",
    "Urdu",
    "Tamil",
    "Kashmiri",
    "Assamese",
    "Bengali",
    "Marathi",
    "Sindhi",
    "Maithili",
    "Punjabi",
    "Malayalam",
    "Manipuri",
    "Telugu",
    "Sanskrit",
    "Nepali",
    "Santali",
    "Gujarati",
    "Odia",
]

COMPLAINT_TYPES = [
    "UPI / Payment Fraud",
    "Credit/Debit Card Fraud",
    "Internet Banking Fraud",
    "Business Email Compromise",
    "Investment / Ponzi Scheme Fraud",
    "Loan / Insurance Fraud",
    "Cryptocurrency Fraud",
    "Job Fraud / Employment Scam",
    "Lottery / Prize Fraud",
    "Social Media Identity Theft",
    "Social Media Hacking",
    "Cyber Bullying / Stalking",
    "Defamation / Fake Profiles",
    "Sextortion / Blackmail",
    "Child Pornography / CSAM",
    "Phishing / Vishing / Smishing",
    "Ransomware Attack",
    "Malware / Virus Attack",
    "Data Breach / Data Theft",
    "DDoS Attack",
    "Website Hacking / Defacement",
    "Email Hacking / Spoofing",
    "SIM Swap Fraud",
    "OTP Fraud",
    "Aadhaar Misuse",
    "E-Commerce Fraud / Fake Delivery",
    "Matrimonial Fraud",
    "Online Gambling / Betting Fraud",
    "Fake App / Software Fraud",
    "Intellectual Property Theft",
    "Cyber Terrorism",
    "Corporate Espionage",
    "Session Hijacking",
    "Man-in-the-Middle Attack",
    "SQL Injection / XSS Attack",
    "Other",
]

REQUIRED_COMPLAINT_FIELDS = [
    "full_name",
    "phone_number",
    "email",
    "address",
    "complaint_type",
    "date_time",
    "description",
    "platform",
]

UNKNOWN_INPUT_HINTS = {
    "transaction_id": "You can find UTR in your bank SMS or transaction history.",
    "date_time": "Check your SMS, app notifications, email timestamps, or browser history.",
    "platform": "Mention the platform where it happened, for example UPI app, Instagram, WhatsApp, or Email.",
    "suspect_details": "Share any known details like phone number, username, account ID, or website link.",
}

STATUS_VALUES = ["pending", "reviewing", "resolved"]
